server:
  port: 7005

params:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/fx?usessl=false
    username: root
    password: password
    maximumPoolSize: 5