server:
  port: 7005

apps:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/app_db?useSSL=false
    username: root
    password: password
    maximumPoolSize: 100